language: ruby
rvm:
- 2.4
branches:
  only:
  - develop
install:
- npm install --global pug
script:
- bundle exec jekyll build
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  on:
    branch: master
env:
  global:
    secure: sVKrR7mEREo70LkNUiKrlHgc1WPWplqjaaG4SgmhOmrHzrlcEC6ICIDAIiDaWHAjER/yDacQUtePdrOChdhjp+m5STMMXqWpgWv9szqAvhzCMXGZMTz72+Pheq1+JNHb6BTlBDWNJriitcBtjEQcUYFPQ8q7YFE5seeMBTrI+J+cuv630MGj1p+MO1bdSV6NwlDxoCZ/emGouhViYrYjZj8tKlV2wGz6lVheyk2Pgv5MniwHfNF11olnGHTrG/R1ajVjTSR02Wg+W/NZcLrUMAraNZRS3Tt99++YetWAoE0FDtKG2wbbsSuTytsNsMiQrWPqU3CaTxpQ3kVEfeZLxMBZxCsJwhJS7V9Y9H568wqgLf++RaybyOWIOEdzKhP4PZt34mSK4OiPYABdwMjkUDzy/kqdsdFxdz0E34PLp1hBRax4eThAFaO+6Ugar1JmDL86u+2HJmAfgwWLgpfSVzhU8tYSUZALoGgVzp7lGisChfhr2T0RSf9Q1qy4ZBCzhV+ulODnap+I4YEMVQMD8Tmjs2lre9Y4kZV177Pq7MBTNd3MOM6wo7b57PsuOGqhJd8R6XB/vXkImF2q2wmf7L3GfIPzfRzClq6rPpnjM9p6BBe2NArzY4fwch0rzoC+ru6ETR13vNchJO1HNJvwirsingri1wSi8dcrba3QlIg=
