---
title: How to learn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
source: src
destination: ./
permalink: "/:categories/:title"
